/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as PlayProjectIdRouteImport } from './routes/play.$projectId'
import { Route as DashboardProjectsRouteImport } from './routes/dashboard/projects'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as DashboardProjectProjectIdIndexRouteImport } from './routes/dashboard/project.$projectId/index'
import { Route as DashboardProjectProjectIdEditRouteImport } from './routes/dashboard/project.$projectId/edit'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const PlayProjectIdRoute = PlayProjectIdRouteImport.update({
  id: '/play/$projectId',
  path: '/play/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProjectsRoute = DashboardProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProjectProjectIdIndexRoute =
  DashboardProjectProjectIdIndexRouteImport.update({
    id: '/project/$projectId/',
    path: '/project/$projectId/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardProjectProjectIdEditRoute =
  DashboardProjectProjectIdEditRouteImport.update({
    id: '/project/$projectId/edit',
    path: '/project/$projectId/edit',
    getParentRoute: () => DashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/explore': typeof ExploreRoute
  '/sign-in': typeof SignInRoute
  '/dashboard/projects': typeof DashboardProjectsRoute
  '/play/$projectId': typeof PlayProjectIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/project/$projectId/edit': typeof DashboardProjectProjectIdEditRoute
  '/dashboard/project/$projectId/': typeof DashboardProjectProjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/sign-in': typeof SignInRoute
  '/dashboard/projects': typeof DashboardProjectsRoute
  '/play/$projectId': typeof PlayProjectIdRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/project/$projectId/edit': typeof DashboardProjectProjectIdEditRoute
  '/dashboard/project/$projectId': typeof DashboardProjectProjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/explore': typeof ExploreRoute
  '/sign-in': typeof SignInRoute
  '/dashboard/projects': typeof DashboardProjectsRoute
  '/play/$projectId': typeof PlayProjectIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/project/$projectId/edit': typeof DashboardProjectProjectIdEditRoute
  '/dashboard/project/$projectId/': typeof DashboardProjectProjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/explore'
    | '/sign-in'
    | '/dashboard/projects'
    | '/play/$projectId'
    | '/dashboard/'
    | '/api/auth/$'
    | '/dashboard/project/$projectId/edit'
    | '/dashboard/project/$projectId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/explore'
    | '/sign-in'
    | '/dashboard/projects'
    | '/play/$projectId'
    | '/dashboard'
    | '/api/auth/$'
    | '/dashboard/project/$projectId/edit'
    | '/dashboard/project/$projectId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/explore'
    | '/sign-in'
    | '/dashboard/projects'
    | '/play/$projectId'
    | '/dashboard/'
    | '/api/auth/$'
    | '/dashboard/project/$projectId/edit'
    | '/dashboard/project/$projectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  ExploreRoute: typeof ExploreRoute
  SignInRoute: typeof SignInRoute
  PlayProjectIdRoute: typeof PlayProjectIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/play/$projectId': {
      id: '/play/$projectId'
      path: '/play/$projectId'
      fullPath: '/play/$projectId'
      preLoaderRoute: typeof PlayProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/projects': {
      id: '/dashboard/projects'
      path: '/projects'
      fullPath: '/dashboard/projects'
      preLoaderRoute: typeof DashboardProjectsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/project/$projectId/': {
      id: '/dashboard/project/$projectId/'
      path: '/project/$projectId'
      fullPath: '/dashboard/project/$projectId/'
      preLoaderRoute: typeof DashboardProjectProjectIdIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/project/$projectId/edit': {
      id: '/dashboard/project/$projectId/edit'
      path: '/project/$projectId/edit'
      fullPath: '/dashboard/project/$projectId/edit'
      preLoaderRoute: typeof DashboardProjectProjectIdEditRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardProjectsRoute: typeof DashboardProjectsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardProjectProjectIdEditRoute: typeof DashboardProjectProjectIdEditRoute
  DashboardProjectProjectIdIndexRoute: typeof DashboardProjectProjectIdIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardProjectsRoute: DashboardProjectsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardProjectProjectIdEditRoute: DashboardProjectProjectIdEditRoute,
  DashboardProjectProjectIdIndexRoute: DashboardProjectProjectIdIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  ExploreRoute: ExploreRoute,
  SignInRoute: SignInRoute,
  PlayProjectIdRoute: PlayProjectIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
